export default {
  login: "reactjs",
  id: 6412038,
  node_id: "MDEyOk9yZ2FuaXphdGlvbjY0MTIwMzg=",
  avatar_url: "https://avatars.githubusercontent.com/u/6412038?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/reactjs",
  html_url: "https://github.com/reactjs",
  followers_url: "https://api.github.com/users/reactjs/followers",
  following_url: "https://api.github.com/users/reactjs/following{/other_user}",
  gists_url: "https://api.github.com/users/reactjs/gists{/gist_id}",
  starred_url: "https://api.github.com/users/reactjs/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/reactjs/subscriptions",
  organizations_url: "https://api.github.com/users/reactjs/orgs",
  repos_url: "https://api.github.com/users/reactjs/repos",
  events_url: "https://api.github.com/users/reactjs/events{/privacy}",
  received_events_url: "https://api.github.com/users/reactjs/received_events",
  type: "Organization",
  site_admin: false,
  name: "React Community",
  company: null,
  blog: "https://reactjs.org",
  location: "Everywhere",
  email: null,
  hireable: null,
  bio: "React website and its localizations",
  twitter_username: null,
  public_repos: 70,
  public_gists: 0,
  followers: 3238,
  following: 0,
  created_at: "2014-01-15T17:46:37Z",
  updated_at: "2022-04-01T07:03:51Z"
};

